<?php

/**
 * @file
 * Provides a directory venue type.
 */

/**
 * Implements hook_localgov_role_default().
 */
function localgov_directories_venue_localgov_roles_default() {
  return [
    // @codingStandardsIgnoreLine
    \Drupal\localgov_roles\RolesHelper::EDITOR_ROLE => [
      'create localgov_directories_venue content',
      'delete any localgov_directories_venue content',
      'delete own localgov_directories_venue content',
      'edit any localgov_directories_venue content',
      'edit own localgov_directories_venue content',
      'revert localgov_directories_venue revisions',
      'view localgov_directories_venue revisions',
    ],
    // @codingStandardsIgnoreLine
    \Drupal\localgov_roles\RolesHelper::AUTHOR_ROLE => [
      'create localgov_directories_venue content',
      'delete own localgov_directories_venue content',
      'edit own localgov_directories_venue content',
    ],
  ];
}
