<?php

/**
 * @file
 * Provides a directory facets entity type.
 */

use Drupal\block\Entity\Block;
use Drupal\Core\Config\FileStorage as ConfigFileStorage;
use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Messenger\MessengerInterface;
use Drupal\Core\Render\Element;
use Drupal\facets\Entity\Facet;
use Drupal\field\FieldConfigInterface;
use Drupal\localgov_directories\DirectoryExtraFieldDisplay;
use Drupal\node\NodeInterface;
use Drupal\pathauto\Entity\PathautoPattern;
use Drupal\search_api\Entity\Index;
use Drupal\search_api\IndexInterface;
use Drupal\search_api\Item\Field as SearchIndexField;
use Drupal\localgov_directories\Constants as Directory;
use Drupal\views\Entity\View;

/**
 * Implements hook_theme().
 */
function localgov_directories_theme() {
  return [
    'localgov_directories_facets' => [
      'render element' => 'elements',
    ],
    'facets_item_list__links__localgov_directories_facets' => [
      'base hook' => 'facets_item_list',
    ],
    // Facet Checkboxes are rendered through Javascript.  So the same markup as
    // "link" Facets suffices.
    'facets_item_list__checkbox__localgov_directories_facets' => [
      'base hook' => 'facets_item_list',
      'template'  => 'facets-item-list--links--localgov-directories-facets',
    ],
  ];
}

/**
 * Implements hook_modules_installed().
 */
function localgov_directories_modules_installed($modules) {
  $services = in_array('localgov_services_navigation', $modules);
  if ($services) {
    \Drupal::service('config.installer')->installOptionalConfig();
    localgov_directories_optional_fields_settings($services);
  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function localgov_directories_entity_extra_field_info() {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(DirectoryExtraFieldDisplay::class)
    ->entityExtraFieldInfo();
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function localgov_directories_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(DirectoryExtraFieldDisplay::class)
    ->nodeView($build, $node, $display, $view_mode);
}

/**
 * Implements hook_pathauto_pattern_alter().
 */
function localgov_directories_pathauto_pattern_alter(PathautoPattern $pattern, array $context) {
  // If pathauto isn't set to include this entity into directory, but
  // it has opt-ed in with the field add the (optional) parent to the path.
  $entity = reset($context['data']);
  assert($entity instanceof ContentEntityInterface);
  if ($entity->hasField('localgov_directory_channels') && strpos($pattern->getPattern(), '[node:localgov_directory_channels:0:entity:url:relative]') === FALSE) {
    $pattern->setPattern('[node:localgov_directory_channels:0:entity:url:relative]/' . $pattern->getPattern());
  }
}

/**
 * Set form settings for optional services and topic fields on installation.
 *
 * @param bool $services
 *   If localgov_services is (being) installed.
 */
function localgov_directories_optional_fields_settings($services) {
  $properties = [
    'targetEntityType' => 'node',
    'bundle' => 'localgov_directory',
  ];
  if ($form_displays = \Drupal::entityTypeManager()->getStorage('entity_form_display')->loadByProperties($properties)) {
    foreach ($form_displays as $form_display) {
      assert($form_display instanceof EntityFormDisplayInterface);
      if ($services && !$form_display->getComponent('localgov_services_parent')) {
        $form_display->setComponent('localgov_services_parent', [
          'type' => 'entity_reference_autocomplete',
          'region' => 'content',
          'settings' => [
            'match_operator' => 'CONTAINS',
            'size' => '60',
            'placeholder' => '',
            'match_limit' => 10,
          ],
          'weight' => 51,
        ])->save();
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 *
 * - Mark new Directory entry content type for indexing.
 * - Display the Directory channel search block on pages of this new Directory
 *   entry content type.
 */
function localgov_directories_field_config_insert(FieldConfigInterface $field) {
  // If a content type can be added to a directory channel add it to the index.
  //
  // While search_api could index more entity types to extend will require
  // updating fields, and aggregating the facet ones. Only 'node' updated here
  // for now.
  if (
    $field->getName() == 'localgov_directory_channels' &&
    $field->getTargetEntityTypeId() == 'node' &&
    ($index = Index::load('localgov_directories_index_default'))
  ) {
    $entity_type_id = 'node';
    $entity_bundle = $field->getTargetBundle();

    $index = Index::load('localgov_directories_index_default');
    $datasource = $index->getDatasource('entity:' . $entity_type_id);
    if (!$datasource) {
      // If the content:node datasource has been lost so have the fields most
      // probably and it's more of a mess. But leaving this here anyway.
      $pluginHelper = \Drupal::service('search_api.plugin_helper');
      $datasource = $pluginHelper->createDatasourcePlugins($index, 'entity:' . $entity_type_id);
    }
    if (!$datasource) {
      \Drupal::messenger()->addMessage(t('Failed to update the directories search index with new bundle'), MessengerInterface::TYPE_ERROR);
      return;
    }

    $configuration = $datasource->getConfiguration();
    $configuration['bundles']['default'] = FALSE;
    if (!in_array($entity_bundle, $configuration['bundles']['selected'])) {
      $configuration['bundles']['selected'][] = $entity_bundle;
    }
    $datasource->setConfiguration($configuration);

    $index_field = $index->getField('rendered_item');
    if ($index_field) {
      $configuration = $index_field->getConfiguration();
      $configuration['view_mode']['entity:node'][$entity_bundle] = 'directory_index';
      $index_field->setConfiguration($configuration);
    }

    $index->save();

    // Also set the default view mode for the directory view listing.
    $view = View::load('localgov_directory_channel');
    if ($view) {
      $display = $view->get('display');
      if (isset($display['node_embed']['display_options']['row'])) {
        $display['node_embed']['display_options']['row']['options']['view_modes']['entity:node'][$entity_bundle] = 'teaser';
      }
      elseif (isset($display['default']['display_options']['row'])) {
        $display['default']['display_options']['row']['options']['view_modes']['entity:node'][$entity_bundle] = 'teaser';
      }
      $view->set('display', $display);
      $view->save();
    }
  }

  // Setup indexing on Facet selection field of a Directory entry content type.
  $is_node_field = $field->getTargetEntityTypeId() === 'node';
  $is_adding_facet_selection_field = $field->getName() === Directory::FACET_SELECTION_FIELD;
  $is_adding_channel_selection_field = $field->getName() === Directory::CHANNEL_SELECTION_FIELD;
  $dir_search_index = Index::load('localgov_directories_index_default');
  $has_dir_search_index = $dir_search_index;

  $entity_bundle = $field->getTargetBundle();
  $entity_field_defs = Drupal::service('entity_field.manager')->getFieldDefinitions('node', $entity_bundle);
  $has_channel_selection_field = array_key_exists(Directory::CHANNEL_SELECTION_FIELD, $entity_field_defs);
  $has_facet_selection_field = array_key_exists(Directory::FACET_SELECTION_FIELD, $entity_field_defs);
  $has_both_facet_and_channel_fields = (($is_adding_channel_selection_field and $has_facet_selection_field) or ($is_adding_facet_selection_field and $has_channel_selection_field));
  $is_new_directory_entry_content_type = ($is_node_field and $has_both_facet_and_channel_fields);
  if ($is_new_directory_entry_content_type and $has_dir_search_index) {
    localgov_directories_add_facet_field_to_index($dir_search_index);
    localgov_directories_create_dir_facet();
  }

  // Setup Directory search block.
  $is_creating_directory_entry_content_type = ($is_node_field and $is_adding_channel_selection_field);
  if ($is_creating_directory_entry_content_type) {
    $content_type = $field->getTargetBundle();
    localgov_directories_add_block_to_content_type_sidebar(Directory::CHANNEL_SEARCH_BLOCK, $content_type);
  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function localgov_directories_field_config_delete(FieldConfigInterface $field) {
  // If a content type can no longer be added to a directory channel remove
  // from index.
  if (
    $field->getName() == 'localgov_directory_channels' &&
    $field->getTargetEntityTypeId() == 'node' &&
    ($index = Index::load('localgov_directories_index_default'))
  ) {
    $entity_type_id = 'node';
    $entity_bundle = $field->getTargetBundle();

    $index = Index::load('localgov_directories_index_default');
    $datasource = $index->getDatasource('entity:' . $entity_type_id);
    if (!$datasource) {
      return;
    }

    $configuration = $datasource->getConfiguration();
    $configuration['bundles']['default'] = FALSE;
    if (($key = array_search($entity_bundle, $configuration['bundles']['selected'])) !== FALSE) {
      unset($configuration['bundles']['selected'][$key]);
    }
    $datasource->setConfiguration($configuration);
    $index->save();
  }

  $is_node_field = $field->getTargetEntityTypeId() === 'node';
  $is_channel_selection_field = $field->getName() === Directory::CHANNEL_SELECTION_FIELD;
  $is_defunct_directory_entry_content_type = ($is_node_field and $is_channel_selection_field);
  if ($is_defunct_directory_entry_content_type) {
    $content_type = $field->getTargetBundle();
    localgov_directories_remove_block_from_content_type_sidebar(Directory::CHANNEL_SEARCH_BLOCK, $content_type);
  }
}

/**
 * Implements theme preprocess_facets_item_list().
 *
 * @see facets_preprocess_facets_item_list()
 */
function localgov_directories_preprocess_facets_item_list(array &$variables) {
  if (!empty($variables['facet']) && ($variables['facet']->id() == 'localgov_directories_facets')) {
    \Drupal::service('class_resolver')
      ->getInstanceFromDefinition(DirectoryExtraFieldDisplay::class)
      ->preprocessFacetList($variables);
  }

}

/**
 * Prepares variables for directory facets templates.
 *
 * Default template: localgov-directories-facets.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the directory facets
 *     information and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_localgov_directories_facets(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Setup indexing on the Facet selection field of Directory entries.
 *
 * This assumes that the localgov_directory_facets_select field is part of a
 * Directory entry content type.
 */
function localgov_directories_add_facet_field_to_index(IndexInterface $dir_search_index) {

  $has_facet_index_field = $dir_search_index->getField(Directory::FACET_INDEXING_FIELD);
  if ($has_facet_index_field) {
    return;
  }

  $new_facet_index_field = new SearchIndexField($dir_search_index, Directory::FACET_INDEXING_FIELD);
  $new_facet_index_field->setLabel('Facets');
  $new_facet_index_field->setDataSourceId('entity:node');
  $new_facet_index_field->setPropertyPath(Directory::FACET_SELECTION_FIELD);
  $new_facet_index_field->setType('integer');
  $new_facet_index_field->setDependencies([
    'config' => [
      'field.storage.node.' . Directory::FACET_SELECTION_FIELD,
    ],
  ]);
  $dir_search_index->addField($new_facet_index_field);
  $dir_search_index->save();
}

/**
 * Import config entity for the directory Facet.
 */
function localgov_directories_create_dir_facet() {

  $has_dir_facet_config = Facet::load(Directory::FACET_CONFIG_ENTITY_ID);
  if ($has_dir_facet_config) {
    return;
  }

  $conditional_config_path = drupal_get_path('module', 'localgov_directories') . '/config/conditional';
  $import_result = localgov_directories_import_config_entity('facets_facet', $conditional_config_path, Directory::FACET_CONFIG_FILE);
  if ($import_result) {
    Drupal::service('config.installer')->installOptionalConfig();
  }
}

/**
 * Create new config entity from given config file.
 *
 * @param string $entity_type
 *   Example: facets_facet.
 * @param string $config_path
 *   Example: modules/foo/config/bar.
 * @param string $config_filename
 *   Example: views.view.bar.
 *
 * @see https://www.metaltoad.com/blog/programmatically-importing-drupal-8-field-configurations
 * @see https://stackoverflow.com/a/52277490
 */
function localgov_directories_import_config_entity(string $entity_type, string $config_path, string $config_filename): bool {

  $config_src = new ConfigFileStorage($config_path);
  if (empty($config_src)) {
    return FALSE;
  }

  $config_values = $config_src->read($config_filename);
  if (empty($config_values)) {
    return FALSE;
  }

  try {
    Drupal::service('entity_type.manager')->getStorage($entity_type)->create($config_values)->save();
  }
  catch (Exception $e) {
    Drupal::service('logger.factory')->get('localgov_directories')->error('Failed to create new config entity: %filename.  Error: %msg', [
      '%filename' => $config_filename,
      '%msg' => $e->getMessage(),
    ]);

    return FALSE;
  }

  return TRUE;
}

/**
 * Update a block's visibility.
 *
 * The given block should appear in pages for the given content type.
 */
function localgov_directories_add_block_to_content_type_sidebar(string $block_id, string $content_type): bool {

  $block_config = Block::load($block_id);
  if (empty($block_config)) {
    Drupal::service('logger.factory')->get('localgov_directories')->error('Block %block-id is missing.  Cannot update its visibility settings.', [
      '%block-id' => $block_id,
    ]);

    return FALSE;
  }

  try {
    $block_visibility_config = $block_config->getVisibility();
    $block_visibility_config['node_type']['bundles'][$content_type] = $content_type;
    $block_config->setVisibilityConfig('node_type', $block_visibility_config['node_type']);
    $block_config->save();
  }
  catch (Exception $e) {
    Drupal::service('logger.factory')->get('localgov_directories')->error('Failed to add %content-type content type to %block-id block: %error-msg', [
      '%content-type' => $content_type,
      '%block-id' => $block_id,
      '%error-msg' => $e->getMessage(),
    ]);

    return FALSE;
  }

  Drupal::service('logger.factory')->get('localgov_directories')->notice('Added %content-type content type to %block-id block.', [
    '%content-type' => $content_type,
    '%block-id' => $block_id,
  ]);

  return TRUE;
}

/**
 * Update a block's visibility.
 *
 * The given block should **not** appear in pages for the given content type.
 */
function localgov_directories_remove_block_from_content_type_sidebar(string $block_id, string $content_type): bool {

  $block_config = Block::load($block_id);
  if (empty($block_config)) {
    Drupal::service('logger.factory')->get('localgov_directories')->error('Block %block-id is missing.  Cannot update its visibility settings.', [
      '%block-id' => $block_id,
    ]);

    return FALSE;
  }

  try {
    $block_visibility_config = $block_config->getVisibility();

    if (empty($block_visibility_config['node_type']['bundles'][$content_type])) {
      return FALSE;
    }

    unset($block_visibility_config['node_type']['bundles'][$content_type]);
    $block_config->setVisibilityConfig('node_type', $block_visibility_config['node_type']);
    $block_config->save();
  }
  catch (Exception $e) {
    Drupal::service('logger.factory')->get('localgov_directories')->error('Failed to remove %content-type content type from %block-id block: %error-msg', [
      '%content-type' => $content_type,
      '%block-id' => $block_id,
      '%error-msg' => $e->getMessage(),
    ]);

    return FALSE;
  }

  Drupal::service('logger.factory')->get('localgov_directories')->notice('Removed %content-type content type from %block-id block.', [
    '%content-type' => $content_type,
    '%block-id' => $block_id,
  ]);

  return TRUE;
}
