<?php

/**
 * @file
 * Provides a directory page type.
 */

/**
 * Implements hook_localgov_role_default().
 */
function localgov_directories_page_localgov_roles_default() {
  return [
    // @codingStandardsIgnoreLine
    \Drupal\localgov_roles\RolesHelper::EDITOR_ROLE => [
      'create localgov_directories_page content',
      'delete any localgov_directories_page content',
      'delete own localgov_directories_page content',
      'edit any localgov_directories_page content',
      'edit own localgov_directories_page content',
      'revert localgov_directories_page revisions',
      'view localgov_directories_page revisions',
    ],
    // @codingStandardsIgnoreLine
    \Drupal\localgov_roles\RolesHelper::AUTHOR_ROLE => [
      'create localgov_directories_page content',
      'delete own localgov_directories_page content',
      'edit own localgov_directories_page content',
    ],
  ];
}
